### PR TITLE
Fix quiz assertion error and cleanup Junits

### LINKED ISSUE #128: Assertion incorrect usage resulting in abrupt termination of program instance
This bug happened for a user input of 'quiz t/yay n/342'.
Can consider removing the assertions completely because in QuizQuestionsManager it actually has an exception that checks for such inputs, can try it in the app and see what is being displayed to the user.

image

image

image

### PR DESCRIPTION
**Pull request by kstonekuan**
Closes #128 and part of #105

### CODE REVIEW

File: src/test/java/seedu/eduke8/Eduke8Test.java [hunk 1]
```diff
@@ -1,12 +1,77 @@
...
+    protected OptionList createTestOptionList() {
+        Option option1 = new Option(PLACEHOLDER_OPTION_ONE_DESCRIPTION);
+        Option option2 = new Option(PLACEHOLDER_OPTION_TWO_DESCRIPTION);
+
+        ArrayList<Displayable> options = new ArrayList<>(
+                Arrays.asList(option1, option2)
+        );
+
+        return new OptionList(options);
     }
```
Comment (Zhi-You) [inline src/test/java/seedu/eduke8/Eduke8Test.java:76]: This is a great idea! Thanks! Now our code looks way cleaner

**Review by Zhi-You — APPROVED** [review]
LGTM! Thanks for helping us change our stuffs too when you add the Eduke8Test class!

**Review by anqi20 — COMMENTED** [review]
Looks awesome! Thank you for cleaning up the testing!
