### PR TITLE
Enhance timer

### LINKED ISSUE #161: Make sure timer continues for any input that is not an answer during quiz

### LINKED ISSUE #164: Do OS dependent inputs for quiz parser
Old implementation did not work for windows, current version doesn't work for headless like WSL (Windows Subsystem for Linux)

### LINKED ISSUE #168: User to press "enter" to trigger next question in quiz mode
So that the timer of the next question doesn't start immediately, it allows the user to read through the explanation first

### LINKED ISSUE #173: [PE-D] Invalid time input accepted for the quiz command
The command input "t/" takes in negative values for time taken, whereby the quiz automatically exhibits all 5 questions and ends immediately. 
My suggestion would be to be more rigorous in the catching of invalid input, with respect to the equivalence partitioning principles as covered in lecture.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kaiwen98/ped#4

### LINKED ISSUE #187: [PE-D] Quiz command bug for time
Putting the time taken for the test as '-1', it will not prompt an error message and will still output as the "user" is doing incorrectly. Maybe create a minimum number of seconds user can input/set a range for it? 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ninggggx99/ped#2

### LINKED ISSUE #197: [PE-D] Issue with entering answer for question
The input does not accept a number with spaces added.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: lingsihui/ped#2

### LINKED ISSUE #199: [PE-D] Issue with timing of the quiz
Maybe you can show an error when user input 0 seconds as the user might input the seconds incorrectly and accidentally see all the answers before doing the quiz! 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: lingsihui/ped#4

### PR DESCRIPTION
**Pull request by anqi20**
Fixes #161 timer continues despite user input (except correct and incorrect answer which will trigger next question / end of quiz) 

Fixes #164 should be able to work across the different OS 

Fixes #168 After every question, user has to press "enter" in order for the next question to be shown / quiz to end. This is so that they have sufficient time to look through the explanation and answer before the next question starts. 

Fixes #173 
Fixes #199 
Fixes #187 timer less than 1 will not be allowed. Error message will be shown 

Fixes #197 user inputs are trimmed

### CODE REVIEW

File: src/main/java/seedu/eduke8/parser/MenuParser.java [hunk 1]
```diff
@@ -129,31 +133,36 @@ public Command parseCommand(DisplayableList topicList, String userInput) {
...
                         topicName = commandArr[1].substring(
                                 commandArr[1].indexOf(TOPIC_INDICATOR) + LENGTH_OF_TOPIC_INDICATOR);
-                        timer = Integer.parseInt(commandArr[2].substring(
+                        userTimer = Integer.parseInt(commandArr[2].substring(
                                 commandArr[2].indexOf(TIMER_INDICATOR) + LENGTH_OF_TIMER_INDICATOR));
                     }
                 }
+                if (userTimer < 1) {
+                    throw new Eduke8Exception(ERROR_QUIZ_TIMER_NON_POSITIVE);
+                }
```
Comment (kstonekuan) [inline src/main/java/seedu/eduke8/parser/MenuParser.java]: Good catching of this error

File: src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java [hunk 2]
```diff
@@ -85,19 +86,23 @@ private void goThroughQuizQuestions(Ui ui, QuizQuestionsManager quizQuestionsMan
...
             assert (command instanceof AnswerCommand || command instanceof HintCommand
                     || command instanceof BookmarkCommand || command instanceof IncompleteCommand);
 
             while (!(command instanceof AnswerCommand || command instanceof IncompleteCommand)) {
                 command.execute(optionList, ui);
                 ui.printQuizInputMessage();
-                command = getCommand(ui, optionList, timer);
+
+                long timePassed = (System.currentTimeMillis() - startTime) / CONVERSION_FROM_SECONDS_TO_MILLIS;
+                command = getCommand(ui, optionList, (int) (userTimer - timePassed));
```
Comment (kstonekuan) [inline src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java:104]: Nice fix to make sure the timer continues after every command

File: src/main/java/seedu/eduke8/ui/Ui.java [hunk 3]
```diff
@@ -134,52 +136,87 @@
...
+    }
+
+    public String getQuizInputFromUser(int timeLeft) throws IOException {
+
+        operatingSystem = findUserOperatingSystem();
+
+        //This is for Linus and Mac operating systems because Robot doesn't work on WSL
+        if (operatingSystem.contains("nux") || operatingSystem.contains("mac")) {
+            BufferedReader userInput = new BufferedReader(new InputStreamReader(System.in));
+            long startingTime = System.currentTimeMillis();
```
Comment (kstonekuan) [inline src/main/java/seedu/eduke8/ui/Ui.java:189]: Good implementation to switch the method based on the operating system

**Review by kstonekuan — APPROVED** [review]
LGTM
