### PR TITLE
Fix Quiz and Ui logic

### LINKED ISSUE #80: Allow user to re-enter an answer for quiz if user did not enter a number
Currently only 'hint' would allow user to re-enter in an answer. Whereas if user type in a word instead of a number, it jumps straight to another question.

### PR DESCRIPTION
**Pull request by Zhi-You**
Fixes #80.

- changed String errorType to String errorMessage since it is technically printing an 
error message to the user instead

- changed MenuParser's text to include more information when printing error message when 
handling incorrectCommands

- allow users to re enter in an answer if they mistakenly entered in an invalid input.

+ might want to make the error messages to constants too.

### CODE REVIEW

File: src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java [hunk 1]
```diff
@@ -75,10 +76,14 @@ private void goThroughQuizQuestions(Ui ui, QuizQuestionsManager quizQuestionsMan
 
             assert (command instanceof AnswerCommand || command instanceof HintCommand);
 
-            while (command instanceof HintCommand) {
+            while (!(command instanceof AnswerCommand)) {
```
Comment (kstonekuan) [inline src/main/java/seedu/eduke8/quiz/SingleTopicQuiz.java:79]: Thanks for changing this, forgot to account for wrong commands

**Review by kstonekuan — APPROVED** [review]
LGTM
