### PR TITLE
Fix menu parser and quiz command error handling

### LINKED ISSUE #101: Invalid topic given to quiz command
image

### PR DESCRIPTION
**Pull request by josephhhhhhhhh**
Closes #101 by fixing mentioned issues. Updated some of the error messages.

### CODE REVIEW

File: src/main/java/seedu/eduke8/command/QuizCommand.java [hunk 1]
```diff
@@ -35,8 +35,12 @@ public void execute(DisplayableList displayableList, Ui ui) {
             SingleTopicQuiz singleTopicQuiz = new SingleTopicQuiz(topic, numOfQuestions);
             singleTopicQuiz.startQuiz(ui);
         } catch (Eduke8Exception e) {
-            LOGGER.log(Level.WARNING, "QuizCommand Execution: An error took place.");
             ui.printError(e.getMessage());
+        } catch (NullPointerException e) {
+            LOGGER.log(Level.WARNING, "QuizCommand Execution: A NullPointerException was thrown.");
+            ui.printError("Error! There is no such topic listed in our storage. Please try again.");
```
Comment (Zhi-You) [inline src/main/java/seedu/eduke8/command/QuizCommand.java:41]: Great job chaining the exceptions!

**Review by Zhi-You — APPROVED** [review]
