### PR TITLE
Fix UI Bugs

### LINKED ISSUE #182: [PE-D] The output format is not consistent.
The output format for some commands, such as "note add/delete/list" and "stats" commands, is not consistent, which lacks of line seperators. The output is a little messy to read.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: JiawenLyu/ped#3

### LINKED ISSUE #195: [PE-D] Error for note displayed wrongly
Should be topic index not name. 

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ninggggx99/ped#10

### LINKED ISSUE #198: [PE-D] Issues with entering the topic name (Suggestion)
Maybe you can list the topics again after it shows the error that it spells incorrectly? 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: lingsihui/ped#3

### PR DESCRIPTION
**Pull request by anqi20**
Fixes #198 a message of asking user to type in "topics" will be shown instead of the entire list of topics 

Fixes #195 
Fixes #182

### CODE REVIEW

File: src/main/java/seedu/eduke8/exception/ExceptionMessages.java [hunk 1]
```diff
@@ -15,7 +15,8 @@
             + " must be more than 0!";
     public static final String ERROR_QUIZ_INSUFFICIENT_TOPIC_QUESTIONS =
             "There is not enough questions in the topic for the quiz!";
-    public static final String ERROR_TOPIC_DOES_NOT_EXIST = "No such topic exists, did you spell it correctly?";
+    public static final String ERROR_TOPIC_DOES_NOT_EXIST = "No such topic exists, did you spell it correctly?"
+            + System.lineSeparator() + "Enter in \"topics\" to get the list of topics.";
```
Comment (kstonekuan) [inline src/main/java/seedu/eduke8/exception/ExceptionMessages.java:19]: Great job making the message more user friendly

File: src/main/java/seedu/eduke8/ui/Ui.java [hunk 2]
```diff
@@ -76,7 +76,7 @@
             + "you earn 2 points if you did not request for hint, "
             + System.lineSeparator() + "and 1 point if you did. No point is awarded for wrong answers.";
     private static final String MESSAGE_GET_INPUT_FROM_USER = "Enter your command or 'help': ";
-    private static final String MESSAGE_GET_INPUT_FROM_USER_QUIZ = "Enter your answer, 'hint' or 'bookmark':";
+    private static final String MESSAGE_GET_INPUT_FROM_USER_QUIZ = "Enter your answer, 'hint' or 'bookmark': ";
```
Comment (kstonekuan) [inline src/main/java/seedu/eduke8/ui/Ui.java:79]: Good catch on the missing space

File: src/main/java/seedu/eduke8/ui/Ui.java [hunk 3]
```diff
@@ -135,6 +135,10 @@
     private static final ExecutorService EXECUTOR_SERVICE = Executors.newFixedThreadPool(1);
     public static final String ERROR_READING_INPUT = "Error reading input.";
     public static final String ERROR_USING_ROBOT = "Error using robot to enter key";
+    public static final String MESSAGE_QUIZ_TO_PROCEED = "Press 'Enter' to proceed!";
+    public static final String OS_NAME = "os.name";
+    public static final String OS_LINUX = "nux";
+    public static final String OS_MAC = "mac";
```
Comment (kstonekuan) [inline src/main/java/seedu/eduke8/ui/Ui.java:141]: Good abstraction

**Review by kstonekuan — APPROVED** [review]
LGTM
